apiVersion: apps/v1
kind: Deployment
metadata:
  name: aquafeed
  labels:
    app.kubernetes.io/name: aquafeed
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: feed-automation
    app.kubernetes.io/part-of: kube-feed
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: aquafeed
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aquafeed
        app.kubernetes.io/version: latest
        app.kubernetes.io/component: feed-automation
        app.kubernetes.io/part-of: kube-feed
    spec:
      imagePullSecrets:
        - name: k8s-ecr-login-renew-docker-secret
      containers:
        - name: main
          image: 456087932636.dkr.ecr.us-west-2.amazonaws.com/kube-feed:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: CONTROLS_PLC_URL
              value: 'http://controls.plc.svc.cluster.local:5000/api/plc'
            - name: KAFKA_BROKERS
              value: 'kafka-kafka-bootstrap.kafka.svc.cluster.local:9092'
            - name: EVENTS_KAFKA_TOPIC
              value: 'feed.automation.events'
            - name: STATE_KAFKA_TOPIC
              value: 'feed.automation.state'
            - name: KAFKA_MAX_BLOCK_MS
              value: '1000'
            - name: KAFKA_RETRIES
              value: '5'
            - name: HTTP_PORT
              value: '80'
            - name: TIMEOUT_MAIN_PHASE_COMPLETED
              value: '30'
            - name: CONTROL_LOOP_SLEEP_PERIOD_MAIN_PHASE
              value: '0.5'
            - name: FEED_STRINGS
              valueFrom:
                configMapKeyRef:
                  name: feed-system-configs
                  key: feed_strings