apiVersion: v1
kind: Service
metadata:
  name: aquafeed
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30220
  selector:
    app.kubernetes.io/name: aquafeed
    app.kubernetes.io/part-of: kube-feed